# Generated by Django 3.2.4 on 2021-06-29 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='post',
            name='recommendations',
            field=models.ManyToManyField(related_name='posts_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(related_name='posts_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
