# Generated by Django 3.2.4 on 2021-07-11 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='posts_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='posts_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
